openapi: 3.0.1
info:
  title: Pre Study
  description: API Documents
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/article:
    post:
      tags:
      - Article
      summary: 게시글 작성 API
      description: 게시글 작성
      operationId: write-article
      parameters:
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      - name: Authorization
        in: header
        description: Authentication Token
        required: true
        schema:
          type: string
        example: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-articles-id486549215"
            examples:
              write-article:
                value: |-
                  {
                    "title" : "테스트 게시글",
                    "content" : "테스트 게시글 입니다.",
                    "password" : "abcDEF09"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id623876813"
              examples:
                write-article:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
  /api/articles:
    get:
      tags:
      - Article
      summary: 게시글 목록 조회 API
      description: 게시글 목록 조회
      operationId: retrieve-articles
      parameters:
      - name: page
        in: query
        description: 현재 페이지
        required: true
        schema:
          type: string
      - name: pageSize
        in: query
        description: 페이지당 게시글 수
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-738887192"
              examples:
                retrieve-articles:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "articles" : [ {
                          "id" : 1,
                          "title" : "테스트",
                          "content" : "테스트 입니다.",
                          "author" : "테스트 작성자",
                          "createdAt" : "2025-07-03T03:48:49.039518Z",
                          "updatedAt" : "2025-07-03T03:48:49.039519Z"
                        } ],
                        "count" : 1
                      }
                    }
  /api/users:
    post:
      tags:
      - User
      summary: 회원 가입 API
      description: 사용자 회원가입
      operationId: user-register
      parameters:
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-users-login-735123830"
            examples:
              user-register:
                value: |-
                  {
                    "username" : "test09",
                    "password" : "abcDEF123"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id623876813"
              examples:
                user-register:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
  /api/articles/{id}:
    get:
      tags:
      - Article
      summary: 게시글 조회 API
      description: 게시글 상세 조회
      operationId: retrieve-article
      parameters:
      - name: id
        in: path
        description: 게시글 ID
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id1007878106"
              examples:
                retrieve-article:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success",
                      "result" : {
                        "id" : 1,
                        "title" : "테스트",
                        "content" : "테스트 입니다.",
                        "author" : "테스트 작성자",
                        "createdAt" : "2025-07-03T03:48:48.840351Z",
                        "updatedAt" : "2025-07-03T03:48:48.840354Z"
                      }
                    }
    delete:
      tags:
      - Article
      summary: 게시글 삭제 API
      description: 게시글 삭제
      operationId: delete-article
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      - name: Authorization
        in: header
        description: Authentication Token
        required: true
        schema:
          type: string
        example: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-articles-id486549215"
            examples:
              delete-article:
                value: |-
                  {
                    "password" : "abcDEF09"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id623876813"
              examples:
                delete-article:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
    patch:
      tags:
      - Article
      summary: 게시글 업데이트 API
      description: 게시글 업데이트
      operationId: update-article
      parameters:
      - name: id
        in: path
        description: ""
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      - name: Authorization
        in: header
        description: Authentication Token
        required: true
        schema:
          type: string
        example: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-articles-id486549215"
            examples:
              update-article:
                value: |-
                  {
                    "title" : "테스트 게시글",
                    "content" : "테스트 게시글 입니다.",
                    "password" : "abcDEF09"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id623876813"
              examples:
                update-article:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
  /api/users/login:
    post:
      tags:
      - User
      summary: 로그인 API
      description: 사용자 로그인
      operationId: user-login
      parameters:
      - name: Accept
        in: header
        description: API 버전 관리를 위한 ACCEPT
        required: false
        schema:
          type: string
        example: application/vnd.pre-study.com-v1+json
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/api-users-login-735123830"
            examples:
              user-login:
                value: |-
                  {
                    "username" : "test09",
                    "password" : "abcDEF123"
                  }
      responses:
        "200":
          description: "200"
          headers:
            Authorization:
              description: Auth 토큰 값
              schema:
                type: string
            Set-Cookie:
              description: Auth Cookie
              schema:
                type: string
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-articles-id623876813"
              examples:
                user-login:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
components:
  schemas:
    api-articles-id623876813:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-users-login-735123830:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호
        username:
          type: string
          description: 사용자 이름
    api-articles-id1007878106:
      type: object
      properties:
        result:
          type: object
          properties:
            createdAt:
              type: string
              description: 게시글 생성 일시
            author:
              type: string
              description: 게시글 작성자
            id:
              type: number
              description: 게시글 ID
            title:
              type: string
              description: 게시글 제목
            content:
              type: string
              description: 게시글 본문
            updatedAt:
              type: string
              description: 게시글 수정 일시
          description: 응답 데이터
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-articles-738887192:
      type: object
      properties:
        result:
          type: object
          properties:
            count:
              type: number
              description: 총 게시글 수
            articles:
              type: array
              description: 게시글 목록
              items:
                type: object
                properties:
                  createdAt:
                    type: string
                    description: 게시글 생성 일시
                  author:
                    type: string
                    description: 게시글 작성자
                  id:
                    type: number
                    description: 게시글 ID
                  title:
                    type: string
                    description: 게시글 제목
                  content:
                    type: string
                    description: 게시글 본문
                  updatedAt:
                    type: string
                    description: 게시글 수정 일시
          description: 응답 데이터
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-articles-id486549215:
      type: object
