openapi: 3.0.1
info:
  title: Pre Study
  description: API Documents
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/users:
    post:
      tags:
      - api
      operationId: user-register
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-users-735123830"
            examples:
              user-register:
                value: |-
                  {
                    "username" : "test09",
                    "password" : "abcDEF123"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/vnd.pre-study.com-v1+json:
              schema:
                $ref: "#/components/schemas/api-users623876813"
              examples:
                user-register:
                  value: |-
                    {
                      "code" : 200,
                      "message" : "success"
                    }
components:
  schemas:
    api-users623876813:
      type: object
      properties:
        code:
          type: number
          description: 응답 코드
        message:
          type: string
          description: 응답 메시지
    api-users-735123830:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호
        username:
          type: string
          description: 사용자 이름
